//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: Claude Code (AI Assistant)
// Created: 2025-09-04
// TimelineEventDto: DTO for issue timeline events display
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using System.ComponentModel;

namespace CleanArchitecture.Blazor.Application.Features.Issues.DTOs;

[Description("Timeline Event")]
public class TimelineEventDto
{
    [Description("Event Id")]
    public Guid Id { get; set; }
    
    [Description("Issue Id")]
    public Guid IssueId { get; set; }
    
    [Description("Event Type")]
    public string Type { get; set; } = default!;
    
    [Description("Event Description")]
    public string Description { get; set; } = default!;
    
    [Description("Event Payload")]
    public string Payload { get; set; } = default!;
    
    [Description("Timestamp")]
    public DateTime Timestamp { get; set; }
    
    [Description("User Name")]
    public string UserName { get; set; } = default!;
    
    [Description("User Id")]
    public string? UserId { get; set; }
    
    [Description("Additional Details")]
    public string? Details { get; set; }
}