//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-04
// Defines permission constants for issue operations (view, create, edit, delete, etc.).
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CleanArchitecture.Blazor.Application.Common.Security;

public static partial class Permissions
{
    [DisplayName("Issue Permissions")]
    [Description("Set permissions for issue operations.")]
    public static class Issues
    {
        [Description("Allows viewing issue details.")]
        public const string View = "Permissions.Issues.View";
        [Description("Allows creating issue records.")]
        public const string Create = "Permissions.Issues.Create";
        [Description("Allows modifying existing issue details.")]
        public const string Edit = "Permissions.Issues.Edit";
        [Description("Allows deleting issue records.")]
        public const string Delete = "Permissions.Issues.Delete";
        [Description("Allows printing issue details.")]
        public const string Print = "Permissions.Issues.Print";
        [Description("Allows searching issue records.")]
        public const string Search = "Permissions.Issues.Search";
        [Description("Allows exporting issue records.")]
        public const string Export = "Permissions.Issues.Export";
        [Description("Allows importing issue records.")]
        public const string Import = "Permissions.Issues.Import";
        [Description("Allows assigning issues to users.")]
        public const string Assign = "Permissions.Issues.Assign";
        [Description("Allows changing issue status.")]
        public const string ChangeStatus = "Permissions.Issues.ChangeStatus";
    }
}

public class IssuesAccessRights
{
    public bool View { get; set; }
    public bool Create { get; set; }
    public bool Edit { get; set; }
    public bool Delete { get; set; }
    public bool Print { get; set; }
    public bool Search { get; set; }
    public bool Export { get; set; }
    public bool Import { get; set; }
    public bool Assign { get; set; }
    public bool ChangeStatus { get; set; }
}