//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-04
//     Last Modified: 2025-09-04
//     Description: 
//       Defines the available views for filtering issues and provides advanced 
//       filtering options for issue lists. This includes pagination and various 
//       filters such as status, priority, category, and user-specific filters.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using System.ComponentModel;
using CleanArchitecture.Blazor.Application.Common.Models;
using CleanArchitecture.Blazor.Application.Common.Security;
using CleanArchitecture.Blazor.Domain.Enums;

namespace CleanArchitecture.Blazor.Application.Features.Issues.Specifications;

#nullable disable warnings
/// <summary>
/// Specifies the different views available for the Issue list.
/// </summary>
public enum IssueListView
{
    [Description("All")]
    All,
    [Description("My Assigned")]
    MyAssigned,
    [Description("My Reported")]
    MyReported,
    [Description("Open")]
    Open,
    [Description("Closed")]
    Closed,
    [Description("Created Today")]
    TODAY,
    [Description("Created within the last 7 days")]
    LAST_7_DAYS,
    [Description("Created within the last 30 days")]
    LAST_30_DAYS
}

/// <summary>
/// A class for applying advanced filtering options to Issue lists.
/// </summary>
public class IssueAdvancedFilter : PaginationFilter
{
    public IssueListView ListView { get; set; } = IssueListView.All;
    public UserProfile? CurrentUser { get; set; }
    
    // Status Filters
    public IssueStatus? StatusFilter { get; set; }
    public IssuePriority? PriorityFilter { get; set; }
    public IssueCategory? CategoryFilter { get; set; }
    
    // Date Range Filters
    public DateTime? DateRangeStart { get; set; }
    public DateTime? DateRangeEnd { get; set; }
    
    // Assignment Filters
    public string? AssignedUserFilter { get; set; }
    
    // Additional Search Fields
    public string? ReferenceNumber { get; set; }
    public string? ReporterName { get; set; }
}