//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: James (Dev Agent)
// Created: 2025-09-04
// UpdateIssuePriorityCommand: Command for updating issue priority with audit logging
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using FluentValidation;
using MediatR;
using CleanArchitecture.Blazor.Application.Common.Interfaces;
using CleanArchitecture.Blazor.Application.Common.Models;
using CleanArchitecture.Blazor.Application.Features.Issues.Caching;
using CleanArchitecture.Blazor.Domain.Enums;

namespace CleanArchitecture.Blazor.Application.Features.Issues.Commands.UpdateIssuePriority;

public class UpdateIssuePriorityCommand : ICacheInvalidatorRequest<Result<Unit>>
{
    public required Guid IssueId { get; set; }
    public required IssuePriority NewPriority { get; set; }
    public string? Reason { get; set; }
    
    public IEnumerable<string>? Tags => IssueCacheKey.Tags;
}

public class UpdateIssuePriorityCommandValidator : AbstractValidator<UpdateIssuePriorityCommand>
{
    public UpdateIssuePriorityCommandValidator()
    {
        RuleFor(x => x.IssueId)
            .NotEmpty()
            .WithMessage("Issue ID is required.");
            
        RuleFor(x => x.NewPriority)
            .IsInEnum()
            .WithMessage("Valid priority is required.");
            
        RuleFor(x => x.Reason)
            .MaximumLength(500)
            .When(x => !string.IsNullOrEmpty(x.Reason))
            .WithMessage("Reason cannot exceed 500 characters.");
    }
}