//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: James (Dev Agent)
// Created: 2025-09-04
// UpdateIssuePriorityCommandHandler: Handles issue priority updates with audit logging
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using Microsoft.EntityFrameworkCore;
using MediatR;
using CleanArchitecture.Blazor.Application.Common.Interfaces;
using CleanArchitecture.Blazor.Application.Common.Models;
using CleanArchitecture.Blazor.Application.Common.Interfaces.Identity;
using CleanArchitecture.Blazor.Domain.Entities;
using System.Text.Json;

namespace CleanArchitecture.Blazor.Application.Features.Issues.Commands.UpdateIssuePriority;

public class UpdateIssuePriorityCommandHandler : IRequestHandler<UpdateIssuePriorityCommand, Result<Unit>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IUserContextAccessor _userContextAccessor;
    
    public UpdateIssuePriorityCommandHandler(
        IApplicationDbContextFactory dbContextFactory,
        IUserContextAccessor userContextAccessor
    )
    {
        _dbContextFactory = dbContextFactory;
        _userContextAccessor = userContextAccessor;
    }
    
    public async Task<Result<Unit>> Handle(UpdateIssuePriorityCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        
        var currentUser = _userContextAccessor.Current;
        if (currentUser?.TenantId == null)
        {
            return await Result<Unit>.FailureAsync("Tenant context not found.");
        }
        
        var issue = await db.Issues
            .Where(i => i.Id == request.IssueId && i.TenantId == currentUser.TenantId)
            .FirstOrDefaultAsync(cancellationToken);
            
        if (issue == null)
        {
            return await Result<Unit>.FailureAsync($"Issue with id: [{request.IssueId}] not found.");
        }
        
        var oldPriority = issue.Priority;
        
        issue.Priority = request.NewPriority;
        issue.LastModified = DateTime.UtcNow;
        issue.LastModifiedBy = currentUser.UserId;
        
        // Create audit log entry
        var eventLog = new EventLog
        {
            Id = Guid.NewGuid(),
            IssueId = issue.Id,
            Type = "priority_changed",
            Payload = JsonSerializer.Serialize(new
            {
                OldPriority = oldPriority.ToString(),
                NewPriority = request.NewPriority.ToString(),
                Reason = request.Reason
            }),
            CreatedUtc = DateTime.UtcNow,
            CreatedBy = currentUser.UserId,
            TenantId = currentUser.TenantId
        };
        
        db.EventLogs.Add(eventLog);
        
        try
        {
            await db.SaveChangesAsync(cancellationToken);
            return await Result<Unit>.SuccessAsync(Unit.Value);
        }
        catch (Exception ex)
        {
            return await Result<Unit>.FailureAsync($"Failed to update issue priority: {ex.Message}");
        }
    }
}