//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: James (Dev Agent)
// Created: 2025-09-04
// AssignIssueCommand: Command for assigning issues to users with notification support
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using FluentValidation;
using MediatR;
using CleanArchitecture.Blazor.Application.Common.Interfaces;
using CleanArchitecture.Blazor.Application.Common.Models;
using CleanArchitecture.Blazor.Application.Features.Issues.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Issues.Commands.AssignIssue;

public class AssignIssueCommand : ICacheInvalidatorRequest<Result<Unit>>
{
    public required Guid IssueId { get; set; }
    public string? AssignedUserId { get; set; } // Null to unassign
    public string? Reason { get; set; }
    
    public IEnumerable<string>? Tags => IssueCacheKey.Tags;
}

public class AssignIssueCommandValidator : AbstractValidator<AssignIssueCommand>
{
    public AssignIssueCommandValidator()
    {
        RuleFor(x => x.IssueId)
            .NotEmpty()
            .WithMessage("Issue ID is required.");
            
        RuleFor(x => x.AssignedUserId)
            .MaximumLength(450)
            .When(x => !string.IsNullOrEmpty(x.AssignedUserId))
            .WithMessage("Assigned User ID cannot exceed 450 characters.");
            
        RuleFor(x => x.Reason)
            .MaximumLength(500)
            .When(x => !string.IsNullOrEmpty(x.Reason))
            .WithMessage("Reason cannot exceed 500 characters.");
    }
}