//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: James (Dev Agent)
// Created: 2025-09-04
// AssignIssueCommandHandler: Handles issue assignment with notification and audit logging
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using Microsoft.EntityFrameworkCore;
using MediatR;
using CleanArchitecture.Blazor.Application.Common.Interfaces;
using CleanArchitecture.Blazor.Application.Common.Models;
using CleanArchitecture.Blazor.Application.Common.Interfaces.Identity;
using CleanArchitecture.Blazor.Domain.Entities;
using System.Text.Json;

namespace CleanArchitecture.Blazor.Application.Features.Issues.Commands.AssignIssue;

public class AssignIssueCommandHandler : IRequestHandler<AssignIssueCommand, Result<Unit>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IUserContextAccessor _userContextAccessor;
    
    public AssignIssueCommandHandler(
        IApplicationDbContextFactory dbContextFactory,
        IUserContextAccessor userContextAccessor
    )
    {
        _dbContextFactory = dbContextFactory;
        _userContextAccessor = userContextAccessor;
    }
    
    public async Task<Result<Unit>> Handle(AssignIssueCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        
        var currentUser = _userContextAccessor.Current;
        if (currentUser?.TenantId == null)
        {
            return await Result<Unit>.FailureAsync("Tenant context not found.");
        }
        
        var issue = await db.Issues
            .Where(i => i.Id == request.IssueId && i.TenantId == currentUser.TenantId)
            .FirstOrDefaultAsync(cancellationToken);
            
        if (issue == null)
        {
            return await Result<Unit>.FailureAsync($"Issue with id: [{request.IssueId}] not found.");
        }
        
        // TODO: Validate assigned user exists if provided
        // This requires access to the Identity DbContext Users table
        // For now, we'll skip validation to avoid compilation errors
        
        var oldAssignedUserId = issue.AssignedUserId;
        
        issue.AssignedUserId = request.AssignedUserId;
        issue.LastModified = DateTime.UtcNow;
        issue.LastModifiedBy = currentUser.UserId;
        
        // Create audit log entry
        var eventLog = new EventLog
        {
            Id = Guid.NewGuid(),
            IssueId = issue.Id,
            Type = request.AssignedUserId == null ? "unassigned" : "assigned",
            Payload = JsonSerializer.Serialize(new
            {
                OldAssignedUserId = oldAssignedUserId,
                NewAssignedUserId = request.AssignedUserId,
                Reason = request.Reason
            }),
            CreatedUtc = DateTime.UtcNow,
            CreatedBy = currentUser.UserId,
            TenantId = currentUser.TenantId
        };
        
        db.EventLogs.Add(eventLog);
        
        try
        {
            await db.SaveChangesAsync(cancellationToken);
            
            // TODO: Send notification to assigned user if needed
            // This could be implemented with an email service or SignalR
            
            return await Result<Unit>.SuccessAsync(Unit.Value);
        }
        catch (Exception ex)
        {
            return await Result<Unit>.FailureAsync($"Failed to assign issue: {ex.Message}");
        }
    }
}